### ISSUE TITLE
configurable CSV structure

### ISSUE THREAD

**Issue by jooaodanieel** [aithana-platform/server#3]
Currently, the input CSV files need to follow a pre-determined structure of columns.

In order to reduce manual work, in which users would need to restructure their spreadsheets structure, it would be better to allow a dynamic mapping between their structure and the tool's

> **suggestion**: allow the user to inform via a CLI argument the path to a YAML file containing the mapping **from the tool's structure** _into the spreadsheet's_

Example:

```yaml
columnsMapping:
  artifactId:
    column: A
    name: "interview id"
  quote:
    column: C
    name: "text fragment"
  section:
    column: D
    name: "chapter"
```
