### ISSUE TITLE
group artifacts into a project

### ISSUE THREAD

**Issue by jooaodanieel** [aithana-platform/server#9]
Currently, the tool handles one artifact at a time.

It would be interesting to group different artifacts of the same research.

> **suggestion**: create a `project` that contains multiple `artifacts`

**Comment by jooaodanieel** [comment]
Another possibility is to have an `project.aithana.yaml` file containing the information about the project

```yaml
aithana:
  project:
    - name: Foo
      context: foo bar baz 
      contextFile: ./data/project.txt
      artifacts:
        - name: foo-bar-baz
          inputFile: ./data/input/foo-bar-baz.csv
          outputFile: ./data/output/foo-bar-baz.csv
```

Where `aithana.project.context` is an alternative to the `aithana.project.contextFile`; as well,  ``aithana.project.artifacts[0].name` defaults the name of the file to `./data/input/{{name}}.csv` so the properties are alternatives to each other
